const ApplicationsActionTypes = {
  CREATE_NEW_APPLICATION_START: 'CREATE_NEW_APPLICATION_START',
  CREATE_NEW_APPLICATION_SUCCESS: 'CREATE_NEW_APPLICATION_SUCCESS',
  CREATE_NEW_APPLICATION_FAILURE: 'CREATE_NEW_APPLICATION_FAILURE',

  UPDATE_EXISTING_APPLICATION_START: 'UPDATE_EXISTING_APPLICATION_START',
  UPDATE_EXISTING_APPLICATION_SUCCESS: 'UPDATE_EXISTING_APPLICATION_SUCCESS',
  UPDATE_EXISTING_APPLICATION_FAILURE: 'UPDATE_EXISTING_APPLICATION_FAILURE',

  DELETE_APPLICATION_START: 'DELETE_APPLICATION_START',
  DELETE_APPLICATION_SUCCESS: 'DELETE_APPLICATION_SUCCESS',
  DELETE_APPLICATION_FAILURE: 'DELETE_APPLICATION_FAILURE',

  GET_ALL_EMPLOYEE_APPLICATIONS_START: 'GET_ALL_EMPLOYEE_APPLICATIONS_START',
  GET_ALL_EMPLOYEE_APPLICATIONS_SUCCESS:
    'GET_ALL_EMPLOYEE_APPLICATIONS_SUCCESS',
  GET_ALL_EMPLOYEE_APPLICATIONS_FAILURE:
    'GET_ALL_EMPLOYEE_APPLICATIONS_FAILURE',

  GET_ALL_JOB_APPLICATIONS_START: 'GET_ALL_JOB_APPLICATIONS_START',
  GET_ALL_JOB_APPLICATIONS_SUCCESS: 'GET_ALL_JOB_APPLICATIONS_SUCCESS',
  GET_ALL_JOB_APPLICATIONS_FAILURE: 'GET_ALL_JOB_APPLICATIONS_FAILURE'
};

export default ApplicationsActionTypes;
