const SavedActionTypes = {
  SAVE_JOB_START: 'SAVE_JOB_START',
  SAVE_JOB_SUCCESS: 'SAVE_JOB_SUCCESS',
  SAVE_JOB_FAILURE: 'SAVE_JOB_FAILURE',

  UNSAVE_JOB_START: 'UNSAVE_JOB_START',
  UNSAVE_JOB_SUCCESS: 'UNSAVE_JOB_SUCCESS',
  UNSAVE_JOB_FAILURE: 'UNSAVE_JOB_FAILURE',

  GET_ALL_EMPLOYEE_SAVED_JOBS_START: 'GET_ALL_EMPLOYEE_SAVED_JOBS_START',
  GET_ALL_EMPLOYEE_SAVED_JOBS_SUCCESS: 'GET_ALL_EMPLOYEE_SAVED_JOBS_SUCCESS',
  GET_ALL_EMPLOYEE_SAVED_JOBS_FAILURE: 'GET_ALL_EMPLOYEE_SAVED_JOBS_FAILURE'
};

export default SavedActionTypes;
