const AdminActionTypes = {
  CREATE_EMPLOYER_START: 'ADMIN_CREATE_EMPLOYER_START',
  CREATE_EMPLOYER_SUCCESS: 'ADMIN_CREATE_EMPLOYER_SUCCESS',
  CREATE_EMPLOYER_FAILURE: 'ADMIN_CREATE_EMPLOYER_FAILURE',

  GET_ALL_EMPLOYERS_START: 'ADMIN_GET_ALL_EMPLOYERS_START',
  GET_ALL_EMPLOYERS_SUCCESS: 'ADMIN_GET_ALL_EMPLOYERS_SUCCESS',
  GET_ALL_EMPLOYERS_FAILURE: 'ADMIN_GET_ALL_EMPLOYERS_FAILURE',

  GET_ALL_EMPLOYEES_START: 'ADMIN_GET_ALL_EMPLOYEES_START',
  GET_ALL_EMPLOYEES_SUCCESS: 'ADMIN_GET_ALL_EMPLOYEES_SUCCESS',
  GET_ALL_EMPLOYEES_FAILURE: 'ADMIN_GET_ALL_EMPLOYEES_FAILURE',

  GET_ALL_ADMINS_START: 'ADMIN_GET_ALL_ADMINS_START',
  GET_ALL_ADMINS_SUCCESS: 'ADMIN_GET_ALL_ADMINS_SUCCESS',
  GET_ALL_ADMINS_FAILURE: 'ADMIN_GET_ALL_ADMINS_FAILURE',

  CHANGE_EMPLOYER_EMAIL_START: 'ADMIN_CHANGE_EMPLOYER_EMAIL_START',
  CHANGE_EMPLOYER_EMAIL_SUCCESS: 'ADMIN_CHANGE_EMPLOYER_EMAIL_SUCCESS',
  CHANGE_EMPLOYER_EMAIL_FAILURE: 'ADMIN_CHANGE_EMPLOYER_EMAIL_FAILURE',

  CHANGE_EMPLOYEE_EMAIL_START: 'ADMIN_CHANGE_EMPLOYEE_EMAIL_START',
  CHANGE_EMPLOYEE_EMAIL_SUCCESS: 'ADMIN_CHANGE_EMPLOYEE_EMAIL_SUCCESS',
  CHANGE_EMPLOYEE_EMAIL_FAILURE: 'ADMIN_CHANGE_EMPLOYEE_EMAIL_FAILURE',

  GET_ALL_EMPLOYER_JOBS_START: 'ADMIN_GET_ALL_EMPLOYER_JOBS_START',
  GET_ALL_EMPLOYER_JOBS_SUCCESS: 'ADMIN_GET_ALL_EMPLOYER_JOBS_SUCCESS',
  GET_ALL_EMPLOYER_JOBS_FAILURE: 'ADMIN_GET_ALL_EMPLOYER_JOBS_FAILURE',

  GET_ALL_EMPLOYEE_APPLICATIONS_START:
    'ADMIN_GET_ALL_EMPLOYEE_APPLICATIONS_START',
  GET_ALL_EMPLOYEE_APPLICATIONS_SUCCESS:
    'ADMIN_GET_ALL_EMPLOYEE_APPLICATIONS_SUCCESS',
  GET_ALL_EMPLOYEE_APPLICATIONS_FAILURE:
    'ADMIN_GET_ALL_EMPLOYEE_APPLICATIONS_FAILURE',

  DELETE_EMPLOYER_START: 'ADMIN_DELETE_EMPLOYER_START',
  DELETE_EMPLOYER_SUCCESS: 'ADMIN_DELETE_EMPLOYER_SUCCESS',
  DELETE_EMPLOYER_FAILURE: 'ADMIN_DELETE_EMPLOYER_FAILURE',

  DELETE_EMPLOYEE_START: 'ADMIN_DELETE_EMPLOYEE_START',
  DELETE_EMPLOYEE_SUCCESS: 'ADMIN_DELETE_EMPLOYEE_SUCCESS',
  DELETE_EMPLOYEE_FAILURE: 'ADMIN_DELETE_EMPLOYEE_FAILURE',

  DELETE_JOB_START: 'ADMIN_DELETE_JOB_START',
  DELETE_JOB_SUCCESS: 'ADMIN_DELETE_JOB_SUCCESS',
  DELETE_JOB_FAILURE: 'ADMIN_DELETE_JOB_FAILURE',

  DELETE_APPLICATION_START: 'ADMIN_DELETE_APPLICATION_START',
  DELETE_APPLICATION_SUCCESS: 'ADMIN_DELETE_APPLICATION_SUCCESS',
  DELETE_APPLICATION_FAILURE: 'ADMIN_DELETE_APPLICATION_FAILURE'
};

export default AdminActionTypes;
