export default [
  'Mandarin',
  'Spanish',
  'English',
  'Hindi',
  'Arabic',
  'Portuguese',
  'Bengali',
  'Russian',
  'Japanese',
  'Punjabi',
  'German',
  'Javanese',
  'Wu (inc. Shanghainese)',
  'Malay (inc. Indonesian and Malaysian)',
  'Telugu',
  'Vietnamese',
  'Korean',
  'French',
  'Marathi',
  'Tamil',
  'Urdu',
  'Turkish',
  'Italian',
  'Yue (inc. Cantonese)',
  'Thai',
  'Gujarati',
  'Jin',
  'Southern Min (inc. Hokkien and Teochew)',
  'Persian',
  'Polish',
  'Pashto',
  'Kannada',
  'Xiang',
  'Malayalam',
  'Sundanese',
  'Hausa',
  'Odia (Oriya)',
  'Burmese',
  'Hakka',
  'Ukrainian',
  'Bhojpuri',
  'Tagalog (Filipino)',
  'Yoruba',
  'Maithili',
  'Uzbek',
  'Sindhi',
  'Amharic',
  'Fula',
  'Romanian',
  'Oromo',
  'Igbo',
  'Azerbaijani',
  'Awadhi',
  'Gan',
  'Cebuano (Visayan)',
  'Dutch',
  'Kurdish',
  'Serbo-Croatian',
  'Malagasy',
  'Saraiki',
  'Nepali',
  'Sinhalese',
  'Chittagonian',
  'Zhuang',
  'Khmer',
  'Turkmen',
  'Assamese',
  'Madurese',
  'Somali',
  'Marwari',
  'Magahi',
  'Haryanvi',
  'Hungarian',
  'Chhattisgarhi',
  'Greek',
  'Chewa',
  'Deccan',
  'Akan',
  'Kazakh',
  'Northern Min',
  'Sylheti',
  'Zulu',
  'Czech',
  'Kinyarwanda',
  'Dhundhari',
  'Haitian Creole',
  'Eastern Min (inc. Fuzhou dialect)',
  'Ilocano',
  'Quechua',
  'Kirundi',
  'Swedish',
  'Hmong',
  'Shona',
  'Uyghur',
  'Hiligaynon/Ilonggo (Visayan)',
  'Mossi',
  'Xhosa',
  'Belarusian',
  'Balochi',
  'Konkani',
  'Other'
];
