const FollowsActionTypes = {
  FOLLOW_EMPLOYER_START: 'FOLLOW_EMPLOYER_START',
  FOLLOW_EMPLOYER_SUCCESS: 'FOLLOW_EMPLOYER_SUCCESS',
  FOLLOW_EMPLOYER_FAILURE: 'FOLLOW_EMPLOYER_FAILURE',

  UNFOLLOW_EMPLOYER_START: 'UNFOLLOW_EMPLOYER_START',
  UNFOLLOW_EMPLOYER_SUCCESS: 'UNFOLLOW_EMPLOYER_SUCCESS',
  UNFOLLOW_EMPLOYER_FAILURE: 'UNFOLLOW_EMPLOYER_FAILURE',

  GET_ALL_EMPLOYEE_FOLLOWS_START: 'GET_ALL_EMPLOYEE_FOLLOWS_START',
  GET_ALL_EMPLOYEE_FOLLOWS_SUCCESS: 'GET_ALL_EMPLOYEE_FOLLOWS_SUCCESS',
  GET_ALL_EMPLOYEE_FOLLOWS_FAILURE: 'GET_ALL_EMPLOYEE_FOLLOWS_FAILURE'
};

export default FollowsActionTypes;
