const CurrentUserActionTypes = {
  SIGN_UP_USER_START: 'SIGN_UP_USER_START',
  SIGN_UP_USER_SUCCESS: 'SIGN_UP_USER_SUCCESS',
  SIGN_UP_USER_FAILURE: 'SIGN_UP_USER_FAILURE',

  SIGN_IN_USER_START: 'SIGN_IN_USER_START',
  SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
  SIGN_IN_USER_FAILURE: 'SIGN_IN_USER_FAILURE',

  LOADING_USER_START: 'LOADING_USER_START',
  LOADING_USER_SUCCESS: 'LOADING_USER_SUCCESS',
  LOADING_USER_FAILURE: 'LOADING_USER_FAILURE',

  SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
  SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
  SIGN_OUT_USER_FAILURE: 'SIGN_OUT_USER_FAILURE',

  DELETE_USER_START: 'DELETE_USER_START',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

  EDIT_EMPLOYEE_INFO_START: 'EDIT_EMPLOYEE_INFO_START',
  EDIT_EMPLOYEE_INFO_SUCCESS: 'EDIT_EMPLOYEE_INFO_SUCCESS',
  EDIT_EMPLOYEE_INFO_FAILURE: 'EDIT_EMPLOYEE_INFO_FAILURE',

  EDIT_EMPLOYEE_AVATAR_START: 'EDIT_EMPLOYEE_AVATAR_START',
  EDIT_EMPLOYEE_AVATAR_SUCCESS: 'EDIT_EMPLOYEE_AVATAR_SUCCESS',
  EDIT_EMPLOYEE_AVATAR_FAILURE: 'EDIT_EMPLOYEE_AVATAR_FAILURE',

  EDIT_EMPLOYEE_EDUCATION_START: 'EDIT_EMPLOYEE_EDUCATION_START',
  EDIT_EMPLOYEE_EDUCATION_SUCCESS: 'EDIT_EMPLOYEE_EDUCATION_SUCCESS',
  EDIT_EMPLOYEE_EDUCATION_FAILURE: 'EDIT_EMPLOYEE_EDUCATION_FAILURE',

  DELETE_EMPLOYEE_EDUCATION_START: 'DELETE_EMPLOYEE_EDUCATION_START',
  DELETE_EMPLOYEE_EDUCATION_SUCCESS: 'DELETE_EMPLOYEE_EDUCATION_SUCCESS',
  DELETE_EMPLOYEE_EDUCATION_FAILURE: 'DELETE_EMPLOYEE_EDUCATION_FAILURE'
};

export default CurrentUserActionTypes;
