const JobsActionTypes = {
  CREATE_NEW_JOB_START: 'CREATE_NEW_JOB_START',
  CREATE_NEW_JOB_SUCCESS: 'CREATE_NEW_JOB_SUCCESS',
  CREATE_NEW_JOB_FAILURE: 'CREATE_NEW_JOB_FAILURE',

  UPDATE_EXISTING_JOB_START: 'UPDATE_EXISTING_JOB_START',
  UPDATE_EXISTING_JOB_SUCCESS: 'UPDATE_EXISTING_JOB_SUCCESS',
  UPDATE_EXISTING_JOB_FAILURE: 'UPDATE_EXISTING_JOB_FAILURE',

  GET_ALL_EMPLOYER_JOBS_START: 'GET_ALL_EMPLOYER_JOBS_START',
  GET_ALL_EMPLOYER_JOBS_SUCCESS: 'GET_ALL_EMPLOYER_JOBS_SUCCESS',
  GET_ALL_EMPLOYER_JOBS_FAILURE: 'GET_ALL_EMPLOYER_JOBS_FAILURE',

  GET_HOME_JOBS_START: 'GET_HOME_JOBS_START',
  GET_HOME_JOBS_SUCCESS: 'GET_HOME_JOBS_SUCCESS',
  GET_HOME_JOBS_FAILURE: 'GET_HOME_JOBS_FAILURE',

  GET_FOLLOWING_JOBS_START: 'GET_FOLLOWING_JOBS_START',
  GET_FOLLOWING_JOBS_SUCCESS: 'GET_FOLLOWING_JOBS_SUCCESS',
  GET_FOLLOWING_JOBS_FAILURE: 'GET_FOLLOWING_JOBS_FAILURE',

  SEARCH_JOBS_START: 'SEARCH_JOBS_START',
  SEARCH_JOBS_SUCCESS: 'SEARCH_JOBS_SUCCESS',
  SEARCH_JOBS_FAILURE: 'SEARCH_JOBS_FAILURE'
};

export default JobsActionTypes;
